### ISSUE TITLE
1주차(7월 12일 ~ 16일) : 이분 탐색  

### ISSUE THREAD

**Issue by jeonghi** [kmu-koss/KMUCS_21_Algorithm#1]
- (참고)인프런 알고리즘 강좌 (c++ 기준) [섹션 2. 42번 ~ 44번](https://www.inflearn.com/course/%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98)/ (python 기준) [섹션 4. 1번 ~4번](https://www.inflearn.com/course/%ED%8C%8C%EC%9D%B4%EC%8D%AC-%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98-%EB%AC%B8%EC%A0%9C%ED%92%80%EC%9D%B4-%EC%BD%94%EB%94%A9%ED%85%8C%EC%8A%A4%ED%8A%B8)
- (참고)[이것이코딩테스트다_이진탐색 강좌](https://www.youtube.com/watch?v=94RC-DsGMLo)
## 1주차 과제
- 백준 온라인 저지 :  [2512번(예산)](https://www.acmicpc.net/problem/2512), [1477번(휴게소 세우기)](https://www.acmicpc.net/problem/1477), [3079번(입국심사)](https://www.acmicpc.net/problem/3079)
- 보너스 문제 (선택사항) : [10816번(숫자카드2)](https://www.acmicpc.net/problem/10816), [3020번(개똥벌레)](https://www.acmicpc.net/problem/3020), [2467번(용액)](https://www.acmicpc.net/problem/2467)
- 코드는 자신의 github 에 알고리즘용 repo 생성한 후 commit. repo 링크 제출
- 복습 레포트는 개인 블로그 또는 README 에 정리 후 댓글로 링크 제출 
 - **7월 17일 토요일 오후 6시 과제 제출 마감**
**7월 17일 토요일 오후 11시 온라인 회의**

**Comment by jeonghi** [comment]
선택사항 문제는 난이도가 조금 있어서 과제를 다 풀고 여유가 있으시면 도전해보시면 좋을것 같습니다. 선택사항의 10816번(숫자카드2) 문제의 경우 파이썬에서 사전 자료구조와 collections.Counter를 사용하지 않고 풀어보세요 :)

**Comment by jeonghi** [comment]
파이썬의 경우 내부적으로 타입을 지정해주기 때문에 개발할때 간편하지만 이는 단점으로도 작용합니다. 타입이 명시적이지 않다는 점은 많은 문제점을 불러 일으킵니다.  [파이썬 3.5 버전에서는 파이썬에서 가독성 향상을 위해 타입 힌트를 문법에 도입](https://lewisxyz000.tistory.com/35)했습니다. 과제 [3079번(입국심사)](https://www.acmicpc.net/problem/3079)의 경우 이러한 타입힌트를  반드시 사용하셔서 변수 타입에 유의하시기 바랍니다.

**Comment by clark1015** [comment]
https://github.com/clark1015/koss_Algorithm

**Comment by yuujinkim** [comment]
https://github.com/yuujinkim/KOSS_Algorithm

**Comment by blkwg** [comment]
https://github.com/blkwg/KOSS_AL

**Comment by clark1015** [comment]
강의
https://junhwanlog.tistory.com/category/Algorithm/inflearn%20python%20algorithm

과제
https://junhwanlog.tistory.com/category/Algorithm/algorithm%20feedback

**Comment by mrgentle1** [comment]
https://github.com/mrgentle1/koss_algorithm/tree/main/%EA%B3%BC%EC%A0%9C/1%EC%A3%BC%EC%B0%A8
