### ISSUE TITLE
2주차(7월 19일 ~ 24일) : 스택, 큐 자료구조

### ISSUE THREAD

**Issue by jeonghi** [kmu-koss/KMUCS_21_Algorithm#2]
- (참고)인프런 알고리즘 강좌 (c++ 기준) [섹션 2. 53번 ~ 55번](https://www.inflearn.com/course/%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98/dashboard)/ (python 기준) [섹션 5. 1번 ~7번](https://www.inflearn.com/course/%ED%8C%8C%EC%9D%B4%EC%8D%AC-%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98-%EB%AC%B8%EC%A0%9C%ED%92%80%EC%9D%B4-%EC%BD%94%EB%94%A9%ED%85%8C%EC%8A%A4%ED%8A%B8/dashboard)
- (참고)[동빈나_실전알고리즘강좌_스택](https://www.youtube.com/watch?v=WB_BoAgWLNU)
- (참고)[동빈나_실전알고리즘강좌_큐](https://www.youtube.com/watch?v=yAiZ1AVU8Aw)
- (참고)[자료구조 코드 시각화](https://swexpertacademy.com/main/visualcode/main.do#/home/mainlayout)
## 2주차 과제
- 이번주는 ~~3주차 DFS/BFS 알고리즘 문제~~를 풀어보기전에 반드시 알아야할 2가지 자료구조 스택과, 큐를 다룹니다
- 3주차는 2주차 배운 스택, 큐의 **심화문제**와 재귀 알고리즘에 대해 다룰 예정입니다.
- DFS/BFS는 4주차부터 진행합니다.  
- 자료구조 이해 및 연습 (**필수**) :  [10828번(스택)](https://www.acmicpc.net/problem/10828),  [18258번(큐)](https://www.acmicpc.net/problem/18258) <- **구현시 라이브러리 사용금지, 직접 클래스 구현할 것**  
- 백준 온라인 저지 (**필수**): [9012번(괄호)](https://www.acmicpc.net/problem/9012), [1918번(후위표기식)](https://www.acmicpc.net/problem/1918), [15828번(라우터)](https://www.acmicpc.net/problem/15828),  <- **반드시 직접 구현한 자료구조 클래스 이용해서 풀기**
- 보너스 문제 (선택사항) : [2493번(탑)](https://www.acmicpc.net/problem/2493), [9935번(문자열 폭발)](https://www.acmicpc.net/problem/9935), [17298번(오큰수)](https://www.acmicpc.net/problem/17298), [2841번(외계인의 기타 연주)](https://www.acmicpc.net/problem/2841), [5397번(키로거)](https://www.acmicpc.net/problem/5397), [2504(괄호의 값)](https://www.acmicpc.net/problem/2504),  [3190번(뱀)](https://www.acmicpc.net/problem/3190) 

- 7월 24일 토요일 오후 6시까지 제출
- 코드는 자신의 github 에 알고리즘용 repo 생성한 후 commit. repo 링크 제출
- 복습 레포트는 개인 블로그 또는 README 에 정리 후 댓글로 링크 제출

**Comment by jeonghi** [comment]
c, c++ 같은 경우 입력 형식이 알고리즘 전체 시간 복잡도 계산에 있어 중요치는 않은데 python 에서는 [유진친구가 사용한 입력 방식](https://github.com/yuujinkim/KOSS_Algorithm/tree/main/%EA%B3%BC%EC%A0%9C/1%EC%A3%BC%EC%B0%A8:%20%EC%9D%B4%EB%B6%84%ED%83%90%EC%83%89#%ED%8C%8C%EC%9D%B4%EC%8D%AC-%EC%9E%85%EB%A0%A5-%EB%B0%9B%EA%B8%B0-sysstdinreadline)을 채택해야 백준에서 통과되는 경우가 있는 것 같아요. 특히나 [15828번](https://www.acmicpc.net/problem/15828) 의 경우에 이러한 방식을 사용해야만 large 케이스를 통과하네요

**Comment by jeonghi** [comment]
언어마다 어느 정도 코딩 스타일 가이드 라인이 존재합니다. 일상 대화에서 국문 맞춤법을 틀리면 핀잔을 받듯이 코딩에서도 마찬가지랍니다. 시간여유가 있을때마다 조금씩 이 [가이드라인](https://www.python.org/dev/peps/pep-0008/)을 읽어보는걸 추천합니다. ( 저는 늦게 시작했는데 많이 후회하고 있어요 ㅜㅜ )

**Comment by jeonghi** [comment]
이번주 정기미팅시간에는 CE에서 중요한 개념인 **Concurrency **(동시성 또는 병렬성) 과 관련한 교육 세션을 진행하려고 합니다. 여러분이 학습하시는 자료구조와 알고리즘이 왜 중요하고 어떻게 쓰이는가에 대한 답이 될 것 같습니다. 스택과 큐에 대한 교육은 별도로 진행되지 않으니 미리 사전에 꼭 학습하시기 바랍니다.

**Comment by clark1015** [comment]
깃허브
https://github.com/clark1015/koss_Algorithm

강의-복습
https://junhwanlog.tistory.com/category/Algorithm/inflearn%20python%20algorithm

과제-복습
https://junhwanlog.tistory.com/category/Algorithm/algorithm%20feedback

**Comment by yuujinkim** [comment]
https://github.com/yuujinkim/KOSS_Algorithm

**Comment by mrgentle1** [comment]
https://github.com/mrgentle1/koss_algorithm/tree/main/%EA%B3%BC%EC%A0%9C/2%EC%A3%BC%EC%B0%A8
