### ISSUE TITLE
3주차(7월 26일 ~ 31일) : 트리, 재귀 알고리즘

### ISSUE THREAD

**Issue by jeonghi** [kmu-koss/KMUCS_21_Algorithm#3]
(참고) [인프런_파이썬_알고리즘 섹션 6. 선수지식 ~ 2번](https://www.inflearn.com/course/%ED%8C%8C%EC%9D%B4%EC%8D%AC-%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98-%EB%AC%B8%EC%A0%9C%ED%92%80%EC%9D%B4-%EC%BD%94%EB%94%A9%ED%85%8C%EC%8A%A4%ED%8A%B8/dashboard)
(참고) [프로그래머스_이시윤 교수님_알고리즘 강좌_트리 파트 17~파트20](https://programmers.co.kr/learn/courses/57) 
(참고) [이코테_동빈나_DFS&BFS](https://www.youtube.com/watch?v=7C9RgOcvkvo&t=1476s)
(참고) [동빈나_실전 알고리즘 강좌_트리와 순회](https://www.youtube.com/watch?v=z_tzHoPfllA)

## 3주차 과제
- 백준 온라인 저지 :  [1991번(트리순회)](https://www.acmicpc.net/problem/1991), [5639번(이진검색트리)](https://www.acmicpc.net/problem/5639), [2263번(트리의순회)](https://www.acmicpc.net/problem/2263), [2504번(괄호의 값)](https://www.acmicpc.net/problem/2504), [3190번(뱀)](https://www.acmicpc.net/problem/3190)
- 보너스 문제 (선택사항) :
- 코드는 자신의 github 에 알고리즘용 repo 생성한 후 commit. repo 링크 제출
- 복습 레포트는 개인 블로그 또는 README 에 정리 후 댓글로 링크 제출 
 - **7월 31일 토요일 오후 6시 과제 제출 마감**
**7월 31일 토요일 오후 11시 온라인 회의**

**Comment by clark1015** [comment]
어려워서 한 문제밖에 못 풀었습니다 ㅠ
복습:
https://junhwanlog.tistory.com/31
문제
https://junhwanlog.tistory.com/30

깃허브
https://github.com/clark1015/koss_Algorithm

**Comment by blkwg** [comment]
https://github.com/blkwg/KOSS_AL/tree/main/3%EC%A3%BC%EC%B0%A8

https://blkwg.tistory.com/21

**Comment by yuujinkim** [comment]
https://github.com/yuujinkim/KOSS_Algorithm

**Comment by mrgentle1** [comment]
https://github.com/mrgentle1/koss_algorithm/tree/main/%EA%B3%BC%EC%A0%9C/3%EC%A3%BC%EC%B0%A8
