### ISSUE TITLE
4주차(8월 9일 ~ 14일) : DFS

### ISSUE THREAD

**Issue by jeonghi** [kmu-koss/KMUCS_21_Algorithm#4]
## 4주차 과제
- [(참고)이것이 코딩테스트다 동빈나_DFS와 BFS](https://www.youtube.com/watch?v=7C9RgOcvkvo&list=PLRx0vPvlEmdAghTr5mXQxGpHjWqSz0dgC&index=3)
- [인프런 파이썬 알고리즘 문제풀이 섹션 6 문제 7번까지 ](https://www.inflearn.com/course/%ED%8C%8C%EC%9D%B4%EC%8D%AC-%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98-%EB%AC%B8%EC%A0%9C%ED%92%80%EC%9D%B4-%EC%BD%94%EB%94%A9%ED%85%8C%EC%8A%A4%ED%8A%B8/dashboard)
- 이번주는 **인프런**강의와 관련된 문제 전부 풀어보고 각자 코드 리뷰진행, 복습일지 작성
- 지난주에 못 풀었던 문제나 복습 일지 함께 제출
- 코드는 자신의 github 에 알고리즘용 repo 생성한 후 commit. repo 링크 제출
- 복습 레포트는 개인 블로그 또는 README 에 정리 후 댓글로 링크 제출 
 - **8월 14일 토요일 오후 6시 과제 제출 마감**
**8월 14일 토요일 오후 11시 온라인 회의**

**Comment by blkwg** [comment]
https://github.com/blkwg/KOSS_AL/tree/main/4%EC%A3%BC%EC%B0%A8

**Comment by yuujinkim** [comment]
https://github.com/yuujinkim/KOSS_Algorithm
